services:
  postgresql:
    image: postgres:18
    container_name: postgre-db
    restart: on-failure
    networks:
      - mybridge
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pw
      POSTGRES_DB: inventory_db
    command: "-c logging_collector=on"
    volumes:
      - postgresql_data:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s

volumes:
  postgresql_data:
    driver: local

networks:
  mybridge:
    driver: bridge